font_family MonoLisa

font_family      family="MonoLisa" wght=500
bold_font        family="MonoLisa" wght=600
italic_font      family="MonoLisa" wght=500 style="SemiBold Italic"
bold_italic_font family="MonoLisa" wght=600 style="Bold Italic"

font_features MonoLisaItalic-SemiBold +ss01 +ss02 +ss03 +ss04 +ss05 +ss06 +ss07 +ss08 +ss09 +ss10 +cv01 +cv02 +liga +calt
font_features MonoLisaItalic-Bold +ss01 +ss02 +ss03 +ss04 +ss05 +ss06 +ss07 +ss08 +ss09 +ss10 +cv01 +cv02 +liga +calt
font_size 16

disable_ligatures never


# Cursor
cursor_shape block
unfocused_cursor_shape block

# No stupid close confirmation
confirm_os_window_close 0

# Use fish shell
shell /usr/bin/fish -c "tmux new-session -A -s main"

# Copy
map ctrl+c    copy_or_interrupt

map ctrl+plus  change_font_size all +1
map ctrl+equal  change_font_size all +1
map ctrl+kp_add  change_font_size all +1
map ctrl+minus       change_font_size all -1
map ctrl+underscore       change_font_size all -1
map ctrl+kp_subtract       change_font_size all -1
map ctrl+0 change_font_size all 0
map ctrl+kp_0 change_font_size all 0
# Disable these shortcuts for neovim harpoon (got used to it)
map ctrl+shift+n no_op

foreground              #C1C9E6
background              #0b0b12
selection_foreground    #0b0b12
selection_background    #F5B8AB

cursor                  #F5B8AB
cursor_text_color       #0b0b12

url_color               #F5B8AB

active_border_color     #00BFFF
inactive_border_color   #464957
bell_border_color       #FACA64

wayland_titlebar_color system
macos_titlebar_color system

active_tab_foreground   #11111a
active_tab_background   #FF8F40
inactive_tab_foreground #C1C9E6
inactive_tab_background #191926
tab_bar_background      #11111a

mark1_foreground #0b0b12
mark1_background #00BBCC
mark2_foreground #0b0b12
mark2_background #FF8F40
mark3_foreground #0b0b12
mark3_background #61BDFF

# The 16 terminal colors

# black
color0 #464957
color8 #676B80

# red
color1 #E66767
color9 #E66767

# green
color2  #70CF67
color10 #70CF67

# yellow
color3  #FACA64
color11 #FACA64

# blue
color4  #00BFFF
color12 #00BFFF

# magenta
color5  #AD6FF7
color13 #AD6FF7

# cyan
color6  #4CD4BD
color14 #4CD4BD

# white
color7  #A3AAC2
color15 #C1C9E6
